import { Inter, Noto_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
})

export const notoSerif = Noto_Serif({
  variable: '--font-notoSerif',
  subsets: ['latin']
})

export const metadata = {
  title: "Tiles Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${notoSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="fixed w-full z-10 bg-white shadow-sm">
          <Navbar />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
